# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b10dc12688ea47870022edc49c4579e64a5882bc5208f8eaa9bbf143e249691c787d26599be84131b813ca1ea6af73f4c7168758df0eb54ad85c36dbb91de1

test:
  secret_key_base: b395b36678ddcf31282d5451ea672c8d8d80f1ecdf8e546fd0877af0fc1300ef6869b7104585ba118157af73e225d4fba5f42d4d6d6c7987bad0c7e991549702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
